name: Build App
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
 
    strategy:
      matrix:
        configuration: [Debug, Release]
 
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
 
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet.exe for use with actions
      # You may pin to the exact commit or the version.
      # uses: NuGet/setup-nuget@a21f25cd3998bf370fde17e3f1b4c12c175172f9
      uses: NuGet/setup-nuget@v2.0.0
      
    - name: Restore NuGet Packages
      run: nuget restore yt-dlp-GUI.sln
      
    - name: Build App
      run: msbuild yt-dlp-GUI.sln /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # tagのバージョン（例：「2.0」）に基づいて、リリースを作成します。

    # まず、コミットされたもののtagを取得します。
    - name: Get Tag
      id: get_tag
      run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

    # つぎに、そのタグを使ってリリースを作成します。
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          yt-dlp-GUI/bin/${{ matrix.configuration }}/yt-dlp-GUI.exe
          yt-dlp-GUI/bin/${{ matrix.configuration }}/yt-dlp-GUI.exe.config
        tag_name: ${{ steps.get_tag.outputs.tag }}
        release_name: Release ${{ steps.get_tag.outputs.tag }}
        body: |
          Changes in this Release
        draft: false
        prerelease: false

    # 最後に、リリースのURLを表示します。
    - name: Get Release URL
      run: echo "The release is at ${{ steps.create_release.outputs.upload_url }}"