name: Build App
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
 
    strategy:
      matrix:
        configuration: [Debug, Release]
 
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
 
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet.exe for use with actions
      # You may pin to the exact commit or the version.
      # uses: NuGet/setup-nuget@a21f25cd3998bf370fde17e3f1b4c12c175172f9
      uses: NuGet/setup-nuget@v2.0.0
      
    - name: Restore NuGet Packages
      run: nuget restore yt-dlp-GUI.sln
      
    - name: Build App
      run: msbuild yt-dlp-GUI.sln /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
 
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        # Artifact name
        name: yt-dlp-GUI_${{ matrix.configuration }}
        # Path of the directory containing the static assets.
        path: yt-dlp-GUI\bin\${{ matrix.configuration }}
 
    # - name: Upload GitHub Pages artifact
    #   uses: actions/upload-pages-artifact@v3.0.1
    #   with:
    #     # Artifact name
    #     name: yt-dlp-GUI_${{ matrix.configuration }}
    #     # Path of the directory containing the static assets.
    #     path: yt-dlp-GUI\bin\${{ matrix.configuration }}