name: build exe

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
          
      - name: Delete old zip
        run: |
          if [[ -f yt-dlp-gui.zip ]]; then
            rm yt-dlp-gui.zip
          fi

      - name: Zip files
        run: zip -r yt-dlp-gui.zip src/dist/windows/gui.exe src/config.json
        
      # 以下、ファイルのコミットとプッシュ
      - name: Commit and Push
        run: |
          git config --global user.email "105225777+github-actions@users.noreply.github.com"
          git config --global user.name "AkaakuHub"
          git add yt-dlp-gui.zip
          git commit -m "Auto commit by GitHub Actions" || exit 0 # ignore error
          git push
