name: build exe

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      - name: test1
        run: ls src/dist
          
      - name: Unzip gui.zip
        run: mkdir temp && mv src/dist/windows/gui.exe temp/gui.exe
        # run: unzip src/dist/windows/gui.zip -d temp

      # - name: Create config.json
      #   run: |
      #     echo '{
      #       "DIR": "C:\\Users\\user\\Videos",
      #       "BROWSER": "firefox"
      #     }' > temp/config.json
          
      - name: Zip files
        run: zip -r result/gui.zip temp/gui.exe temp/config.json
        
      - uses: actions/upload-artifact@v2
        with:
          name: gui
          path: result
